Feat: 🎨  get profile
ido123ziv/openu-web-develop-20995 pull request #42
Opened 2024-05-15 20:10 UTC by ido123ziv

as for: https://trello.com/c/9rOpKHYE/45-getprofile
getting parent:
```json
[
  {
    "parent_id": 1,
    "parent_name": "Dilen",
    "email": "dilen@test.com",
    "password": "$2a$12$0B.EaJM27vxqP7kZbzdbcukfKbVaPKnfyAvggeVWMB8MT/fFEmQMG",
    "city": "Haifa",
    "street": "Habonim",
    "phone_number": "0500041247",
    "gender": "F",
    "min_kid_age": 1,
    "max_kid_age": 1,
    "num_of_kids": 1,
    "end_timestamp": "9999999999",
    "start_timestamp": "0",
    "comments": "The Bex"
  }
]
```
getting babysitter
```json
[
  {
    "babysitter_id": 1,
    "babysitter_name": "Amit",
    "email": "amit@test.com",
    "password": "$2a$12$0B.EaJM27vxqP7kZbzdbcukfKbVaPKnfyAvggeVWMB8MT/fFEmQMG",       
    "city": "Holon",
    "street": "Arlozorov",
    "experience": "mid",
    "age": 20,
    "phone_number": "0505050050",
    "gender": "F",
    "working_hours": {
      "monday": "9am-3pm",
      "tuesday": "9am-3pm",
      "wednesday": "9am-3pm",
      "thursday": "9am-3pm",
      "friday": "9am-3pm"
    },
    "end_timestamp": "9999999999",
    "start_timestamp": "0",
    "image_string": "",
    "comments": "I need a job, please hire me."
  }
]
```

2024-05-17 11:38 UTC, shellytesler requested changes

2024-05-17 11:38 UTC, shellytesler commented on server/routes/api/profile/profileDBHandler.ts
> +        const babysitterQuery = `SELECT *
Write exactly what columns you want from the select * and you need to format it to fit the type you are returning.
For example - phone_number to phoneNumber

2024-05-17 11:38 UTC, shellytesler commented on server/routes/api/profile/profileDBHandler.ts
> +        const parentQuery = `SELECT *
same here

2024-05-19 07:49 UTC, EliGandin approved these changes
Great Work

2024-05-19 08:20 UTC, merged