Profile
ido123ziv/openu-web-develop-20995 pull request #56
Opened 2024-05-25 17:32 UTC by EliGandin

2024-05-26 14:43 UTC, shellytesler requested changes
Comments in general:
1. the sub menu for a babysitter is way to big
2. I don't like that when the babysitter goes to profile it doesn't let her edit the profile - only to override it. What if the babysitter wrote a lot of comments and she just wants to edit it?
3.

2024-05-27 13:57 UTC, shellytesler requested changes

2024-05-27 13:57 UTC, shellytesler commented on client/src/pages/profile/BabysitterProfile/BabysitterProfile.tsx
> +      deleteProfile(user.id);
why dont you await?

2024-05-27 13:57 UTC, shellytesler commented on client/src/ui/Layout.tsx
> +        <Route path="/babysitter/profile/:id" element={<BabysitterProfile />} />
run the project - it doesnt work - these rows make it fail

2024-05-28 08:24 UTC, shellytesler approved these changes

2024-05-29 08:16 UTC, liela9 commented on server/routes/api/delete/deleteUserHandler.ts
> +    if (Number(parentProfile[0].endTimestamp) !== END_TIMESTAMP) {
i beleave it should be != instead of !==
When you test it does it work? (it didn't work to me)

2024-05-29 08:16 UTC, liela9 commented on server/routes/api/delete/deleteUserHandler.ts
> +    if (Number(babysitterProfile[0].endTimestamp) !== END_TIMESTAMP) {
same here

2024-05-29 10:19 UTC, merged