Bugs fix
ido123ziv/openu-web-develop-20995 pull request #57
Opened 2024-05-26 14:27 UTC by EliGandin

2024-05-26 14:44 UTC, shellytesler requested changes

2024-05-26 14:44 UTC, shellytesler commented on server/routes/api/recommendations/recommendationsRoutes.ts
> +      const parentValidation = await handler.parentValidation(Number(parentId));
Here you call a validation function in the handler and that validation function calls the other 2 validations in the hadnler.
So the route only calls 1

2024-05-26 18:23 UTC, ido123ziv commented
**You fixed the bugs!**
* testing on branch created today from main: https://github.com/ido123ziv/openu-web-develop-20995/actions/runs/9245298200
* testing on your branch: https://github.com/ido123ziv/openu-web-develop-20995/actions/runs/9245288503

In this pr you can take the automated input check with latest config: https://github.com/ido123ziv/openu-web-develop-20995/pull/58

2024-05-27 07:12 UTC, shellytesler approved these changes
Nicee

2024-05-27 07:13 UTC, merged